void usage(void)
BOOL ptr_port_init(UWORD port)
void lynxit_shift_out_byte(UBYTE data)
UBYTE lynxit_shift_in_byte(void)
void lynxit_write_control(UBYTE data)
void lynxit_write_page(UBYTE page)
void lynxit_counter_reset(void)
void lynxit_counter_increment(void)
UBYTE cart_read_byte(UWORD cart)
void cart_write_byte(UWORD cart,UBYTE data)
void cart_read_page(UWORD cart,UWORD page_number,UWORD page_size,UBYTE *page_ptr)
void cart_write_page(UWORD cart,UWORD page_number,UWORD page_size,UBYTE *page_ptr)
SWORD cart_analyse(cart)
BOOL cart_verify(UBYTE *filename)
BOOL cart_read(UBYTE *filename)
BOOL cart_write(UBYTE *filename)
BOOL perform_test(UBYTE *testname)
void main(SWORD argc,UBYTE **argv)
