
<table border="0" bgcolor="#ffffff" width="610">
  <tr>
    <td><font size="-1">
<img src="images/ucon64misc.png" border="0" height="50"><font size="-1"><br>
<br>
<a href="ucon64misc/conn.html">conn.html</a> (html)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/conn.pdf?download">conn.pdf</a> (pdf)<br>
Quick guide to the most Video Game Connectors and Cables<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/cxa1645.pdf?download">cxa1645.pdf</a><br>
CXA1645P/M is an RGB encoder used in many consoles and other video hardware<br>
These specifications were made for you if your console lacks S-Video or RGB
and IF you have some knowledge about electronics<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/faqs.zip?download">faqs.zip</a> (~1.1 MB)<br>
A loose collection of FAQ's about Hardware, modifications like PAL/NTSC
switches, or backup unit manuals<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/custom.zip?download">custom.zip</a><br>
Selfmade read-only backup unit for Super Nintendo and Sega Mega Drive with sources and PCB layouts (not tested)<br>
<!--br>
<a href="http://prdownloads.sourceforge.net/ucon64/warppipe-0.1.3-gpl-src.tar.gz?download">warppipe-0.1.3-gpl-src.tar.gz</a><br>
<a href="http://prdownloads.sourceforge.net/ucon64/warppipe-0.1.3-gpl-src.zip?download">warppipe-0.1.3-gpl-src.zip</a><br>
This is the release of the latest WarpPipe version with GPL license (as found
on Sourceforge CVS).<br>
This project is free for "adoption" since all original developers forked to a
closed source project with the same name but a different license.<br>
--><br>
<img src="images/dos.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/userport.zip?download">userport.zip</a><br>
<a href="http://prdownloads.sourceforge.net/ucon64/giveio.zip?download">giveio.zip</a><br>
I/O port driver for Windows NT, Windows 2000 or Windows XP<br>
Only necessary to access the parallel port<br>
<br>
<img src="images/dos.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/vgs.zip?download">vgs.zip</a><br>
Original sources of VGS the well-known transfer tool from JSI<br>
<br>
<img src="images/dos.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/dos32.zip?download">dos32.zip</a><br>
<a href="http://prdownloads.sourceforge.net/ucon64/dos4gw.zip?download">dos4gw.zip</a><br>
<a href="http://prdownloads.sourceforge.net/ucon64/csdpmi5b.zip?download">csdpmi5b.zip</a><br>
Some DOS extenders/DPMI hosts. uCON64 needs the files in csdpmi5b.zip under plain DOS (DOS without Windows)<br>
<br>
<img src="images/win32.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/port95nt.exe?download">port95nt.exe</a><br>
One of the three DLL I/O port drivers supported by the Windows versions of uCON64 (see the FAQ for links to the other two)<br>
Only necessary to access the parallel port<br>
<br>
<img src="images/win32.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/zlib.zip?download">zlib.zip</a><br>
zlib.dll<br>
<br>
<a href="http://www.cygwin.com"><img src="images/cygwin-icon.png" border="0"></a> (Cygwin)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/cygwindll.zip?download">cygwindll.zip</a><br>
<a href="http://prdownloads.sourceforge.net/ucon64/cygzdll.zip?download">cygzdll.zip</a><br>
Needed by the uCON64 Cygwin port to work<br>
<br>
<img src="images/beos.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/ioport.zip?download">ioport.zip</a><br>
I/O port driver from <a href="http://www.infernal.currantbun.com/">Caz</a><br>
Only necessary to access the parallel port<br>
<br>
<img src="images/fal.png" width="60"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/preboot32.zip?download">preboot32.zip</a><br>
Loader for Flash Advance Linker (uCON64 options: --multi, --xfalmulti, --xfal)<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/mdpacku4.zip?download">mdpacku4.zip</a><br>
Loader for MD-PRO (uCON64 options: --multi, --xmd)<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/smsdbug3.zip?download">smsdbug3.zip</a><br>
Loader for SMS-PRO (uCON64 options: --multi, --xgg)<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/ggdbug3.zip?download">ggdbug3.zip</a><br>
Loader for GG-PRO (uCON64 options: --multi, --xgg)<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/pceboot.zip?download">pceboot.zip</a><br>
Loader for PCE-PRO (uCON64 options: --multi, --xpce)<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/sfbotx2.zip?download">sfbotx2.zip</a><br>
Loader for Super Flash (uCON64 options: --multi, --xsf)<br>
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/xmcd-iso.zip?download">xmcd-iso.zip</a><br>
ISO's containing Genesis binaries to communicate with a Genesis via Mike Pavone's cable (uCON64 option: --xmcd)<br>
See <a href="http://www.retrodev.com">http://www.retrodev.com</a> for more information<br>
<br>
<img src="images/n64.png" width="30"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/sram_1bs.zip?download">sram_1bs.zip</a><br>
Memory Manager 1.0 beta<br>
By R. Bubba Magillicutty<br>
16 MBit Version (uCON64 options: --xv64, --xdjr)<br>
<br>
<img src="images/n64.png" width="30"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/bb-sram2.zip?download">bb-sram2.zip</a><br>
SRAM Manager 2.0 is a save game memory management utility for use with
Nintendo 64 memory paks and cartridges. (uCON64 options: --xv64, --xdjr)<br>
This utility is based on R. Bubba's original SRAM Manager 1.0b<br>
<br>
<img src="images/n64.png" width="30"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/nil-jrbu.zip?download">nil-jrbu.zip</a><br>
This allows the Doctor V64 Junior to backup 512M carts<br>
Send this program to your V64 Junior and then turn on the N64, it will then read
512M from the cart into its DRAM (even if the cart is smaller)<br>
Then you transfer the data from DRAM to your workstation<br>
<br>
<img src="images/n64.png" width="30"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/upsram11.zip?download">upsram11.zip</a><br>
LaC's N64 ROM that can be used to upload SRAM-savegames directly to the V64 (uCON64 options: --xv64, --xdjr)<br>
<br>
<img src="images/n64.png" width="30"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/ultrasmsv10.zip?download">ultrasmsv10.zip</a><br>
Sega Master System/Game Gear emulator for Nintendo 64 by Jos Kwanten<br>
(uCON64 option: --usms)<br>
<br>
<img src="images/gameboy.png" width="60"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/fcgb2.lzh?download">fcgb2.lzh</a><br>
NES emulator for GameBoy by Kami (uCON64 option: --n2gb)<br>
<br>
<img src="images/gameboy.png" width="60"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/gbpack13.zip?download">gbpack13.zip</a><br>
Menu program for multiple ROM files in one GB Card. Works with all versions of
Game Boy. Supports GB Card (64 Mbit)<br>
<br>
<img src="images/lynx.png" width="60"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/lynxit11.zip?download">lynxit11.zip</a><br>
Lynxit is a custom made backup unit for the Atari Lynx handheld<br>
(uCON64 option: --xlit)<br>
<br>
<img src="images/f2a.png" width="60"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/f2afilesv4.zip?download">f2afilesv4.zip</a><br>
Flash 2 Advance (Ultra) support files<br>
(uCON64 options: --xf2a, --xf2amulti, --xf2ac, --xf2as, --xf2ab)<br>
<br>
<img src="images/sc.png"><br>
<a href="http://prdownloads.sourceforge.net/ucon64/supercard_menu.zip?download">supercard_menu.zip</a><br>
Super Card (CF to GBA Adapter) support files<br>
(uCON64 option: --sc)<br>
    </td>
  </tr>
</table>
