<table border="0" bgcolor="#ffffff" width="610">
  <tr>
    <td valign="top"><font size="-1">
<!-- keep them in one line or they'll look fucked up in mozilla -->
<a href="ucon64/faq.html">FAQ</a>|<a href="ucon64/developers.html#3">CVS</a>|<a href="mailto:ucon64-main@lists.sf.net">Bugs?</a>|<a href="mailto:ucon64-main@lists.sf.net">Contact</a>
<br>
<center>
<img src="images/black.png" height="10" width="590">
</center><font size="-1">
<img src="images/ucon64dat_small.png" border="0" height="50"><br>
<br>
Completely new, tested and working DAT files for all known ROMs generated with uCON64 (uCON64 option: --mkdat=DATFILE)<br>
You may read the <a href="ucon64/faq.html">FAQ</a> or just put them into ~/.ucon64/dat/ (might depend on which platform you use)<br>
They should also work with other ROM checking tools<br>
<br>
<center>
<img src="images/black.png" height="10" width="590">
</center>
<img src="images/download.png"><br><font size="-1">
<br>
<a href="http://prdownloads.sourceforge.net/ucon64/snes-even-better.zip?download">
  snes-even-better.zip</a> (by JohnDie and dbjh with many thanks to Cowering and Nach)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/gen-20031115.zip?download">
  gen-20031115.zip</a> (by pauloB)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/gg-20031115.zip?download">
  gg-20031115.zip</a> (by pauloB)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/sms-20031115.zip?download">
  sms-20031115.zip</a> (by pauloB)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/n64-20031115.zip?download">
  n64-20031115.zip</a> (by pauloB)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/fds-20031116.zip?download">
  fds-20031116.zip</a> (by pauloB)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/pce-20031116.zip?download">
  pce-20031116.zip</a> (by pauloB)<br>
<a href="http://prdownloads.sourceforge.net/ucon64/nes-20031208.zip?download">
  nes-20031208.zip</a> (by JohnDie)<br>
to be continued...<br>
<br>
For more DAT files see <a href="http://emulationrealm.net/rcdat.php#Cowering_GoodTools">http://emulationrealm.net/</a> or <a href="http://www.gbadat.altervista.org">http://www.gbadat.altervista.org</a><br>
    </td>
  </tr>
</table>
