<table border="0" bgcolor="#ffffff" width="610">
  <tr>
    <td valign="top">
<font size="-1">
<br>
<center><img src="images/new.png" border="0" width="200"></center>
<br>
<!--NEWS-->
20061110 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#ucon64">The uCON64 CVS version is currently broken due to heavy<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;development</a><br>
<a name="flc">20060923 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://flc.berlios.de">flc has been moved to its own site</a><br>
20060914 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#flc">flc 1.4.1 has been released</a><br>
20060412 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#flc">flc 1.4.0 has been released</a><br>
20050312 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#ucon64gui">uCON64 frontend 1.1 released (including a Mac OS X binary)</a><br>
20050126 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#download">Amiga binaries of uCON64 2.0.0 available</a><br>
20050107 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#ucon64gui">uCON64 frontend 1.0 released</a><br>
20050107 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#ucon64">uCON64 2.0.0 released</a><br>
20041028 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="ucon64/hardware.html">updated hardware list (current CVS version of uCON64)</a><br>
20041028 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#flc">unexpected release of flc 1.2.0</a><br>
20040319 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#ucon64">uCON64 1.9.8-4 released</a><br>
<br>
<img src="images/black.png" height="10" width="590">
<br>
<br>
<center><img src="images/rss.png" border="0" width="200"><br>Bookmarks</center>
<br>
<br>
<!--RSS NEWS-->
20061009 04:33 <a href="http://youtube.com/?v=S-oWbORk44A">gp2x odessey2 emulator</a><br>
20061007 21:25 <a href="http://youtube.com/?v=IPwTOmMliMc">Rolo to the Rescue GEN pres. by SpeedRuns.net</a><br>
20061007 21:23 <a href="http://youtube.com/?v=6A_hOYR6BII">Emulator CM2</a><br>
20061007 07:22 <a href="http://youtube.com/?v=6nEbh-kT8ug">Atari Lynx emulator on GP2X</a><br>
20061006 22:28 <a href="http://youtube.com/?v=6aCRZyZnHe0">2_04_5-5</a><br>
20061006 19:02 <a href="http://youtube.com/?v=FLTxkqmt2dU">ULTAMATE MARIO</a><br>
20061004 20:05 <a href="http://youtube.com/?v=1SEfghfnMEc">Ace Combat on psx4all on GP2X</a><br>
20061004 20:00 <a href="http://youtube.com/?v=480krfxM1hk">RR4 on psx4all on GP2X</a><br>
20061004 19:56 <a href="http://youtube.com/?v=vEHIaDZ9H8k">Rapid Reload on psx4all on GP2X</a><br>
20061004 19:50 <a href="http://youtube.com/?v=RG1JhBPZAbI">FF7 on psx4all on GP2X</a><br>
20061003 10:49 <a href="http://youtube.com/?v=OV8hqTd-RtA">sonic 2 capital city zone with shadow</a><br>
20060926 21:31 <a href="http://youtube.com/?v=SO6JJxGhAAo">Metal Slug X on the psp</a><br>
20060924 15:13 <a href="http://youtube.com/?v=m_CSEE_mQ1c">operation moon gate</a><br>
20060924 14:44 <a href="http://youtube.com/?v=roh-Azn31qU">PS1 EMULATOR ON  PSP</a><br>
20060915 21:51 <a href="http://youtube.com/?v=sQ9vewU1aag">snes on psp</a><br>
20060912 22:53 <a href="http://youtube.com/?v=vqT8iUhUVk0">PSP Tiff Homebrew Tetris on 2.8</a><br>
20060912 11:21 <a href="http://youtube.com/?v=oaEZIhJc7_M">My super mario</a><br>
20060903 12:42 <a href="http://youtube.com/?v=S_l_fZEHnq0">GP2x - Sega systems emulator</a><br>
20060829 22:00 <a href="http://youtube.com/?v=mlwq3v4uQBM">Photo Feature of  GP2x (Clip 2)</a><br>
20060829 21:42 <a href="http://youtube.com/?v=P6l60-Enc4I">GP2x Photo Feature</a><br>
20060829 20:56 <a href="http://youtube.com/?v=24WbKTzcBEU">Game Boy (Color) Emulation on GP2x</a><br>
20060829 20:48 <a href="http://youtube.com/?v=nn6Q30C2YrY">MAME Emulation on the GP2x (Clip 1)</a><br>
20060829 20:14 <a href="http://youtube.com/?v=t6QEEasmxLY">Duke Nukem 3D on GP2x</a><br>
20060829 17:11 <a href="http://youtube.com/?v=QdKjGHpY_H8">MAME Emulation on the GP2x (Clip 2)</a><br>
20060829 16:39 <a href="http://youtube.com/?v=J03di9c18BY">Sega Genesis Emulation on the GP2x</a><br>
20060828 01:22 <a href="http://youtube.com/?v=Idh80aDaQGQ">Home brew on all PSPs!!!!</a><br>
20060827 07:33 <a href="http://youtube.com/?v=LGLPngi5ogY">Emulation of halo 2 on DS</a><br>
20060826 06:16 <a href="http://youtube.com/?v=h6UBCrKMDuk">Sony VGN-U50: N64 emulator</a><br>
20060824 15:46 <a href="http://youtube.com/?v=nxdMRCb7rMY">gp2xtr.com Intro Video - Part I</a><br>
20060822 23:17 <a href="http://youtube.com/?v=t_GYAdwd9I8">sega emul on my xbox</a><br>
<br>
updated with RSStool 0.9.4 20061011 20:37:39
    </td>
  </tr>
</table>
