#ifndef LIBHTK_DEFINES_H
#define LIBHTK_DEFINES_H

#define stricmp strcasecmp
#define strnicmp strncasecmp

#define WIDGET_INPUT_TEXT 1
#define WIDGET_INPUT_FILE 2
#define WIDGET_INPUT_FILEDIALOG 3
#define WIDGET_BUTTON 4
#define WIDGET_INPUT_IMAGE 5
#define WIDGET_INPUT_RESET 6
#define WIDGET_INPUT_CHECKBOX 7
#define WIDGET_INPUT_RADIO 8
#define WIDGET_TEXTAREA 9
#define WIDGET_SELECT 10
#define WIDGET_HTML 11
#define WIDGET_HTML_END 12
#define WIDGET_TITLE 13
#define WIDGET_BODY 14
#define WIDGET_BODY_END 15
#define WIDGET_HEAD 16
#define WIDGET_HEAD_END 17
#define WIDGET_FORM 18
#define WIDGET_FORM_END 19
#define WIDGET_IMG 20
#define WIDGET_PRINTF 21
#define WIDGET_HR 22
#define WIDGET_BR 23

#define WIDGET_INPUT_SUBMIT 24

#endif // LIBHTK_DEFINES_H
